apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka-broker
spec:
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
  selector:
    app: kafka-broker
  type: LoadBalancer